// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-dossiers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_dossiers_default = defineTool({
  name: "list_dossiers",
  title: "Lister les dossiers",
  description: "Liste les dossiers judiciaires accessibles \xE0 l'utilisateur connect\xE9 (filtr\xE9s par RLS).",
  inputSchema: {
    status: z.string().optional().describe("Filtrer par statut (ex: en_cours, transmis, cloture)."),
    limit: z.number().int().min(1).max(100).optional().describe("Nombre max (d\xE9faut 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("dossiers").select("id, reference, titre, status, priority, type_infraction, lieu, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { dossiers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-dossier.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_dossier_default = defineTool2({
  name: "get_dossier",
  title: "D\xE9tails d'un dossier",
  description: "R\xE9cup\xE8re le d\xE9tail complet d'un dossier par son identifiant.",
  inputSchema: {
    id: z2.string().uuid().describe("UUID du dossier.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("dossiers").select("*").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Dossier introuvable" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { dossier: data }
    };
  }
});

// src/lib/mcp/tools/search-dossiers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_dossiers_default = defineTool3({
  name: "search_dossiers",
  title: "Rechercher des dossiers",
  description: "Recherche des dossiers par mot-cl\xE9 sur la r\xE9f\xE9rence, le titre ou la description.",
  inputSchema: {
    query: z3.string().min(1).describe("Terme de recherche."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const pattern = `%${query}%`;
    const { data, error } = await supabaseForUser3(ctx).from("dossiers").select("id, reference, titre, status, type_infraction, created_at").or(
      `reference.ilike.${pattern},titre.ilike.${pattern},description.ilike.${pattern}`
    ).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gfdreaizinkmwqcrekwr";
var mcp_default = defineMcp({
  name: "justicelink-mcp",
  title: "JusticeLink MCP",
  version: "0.1.0",
  instructions: "Outils MCP JusticeLink pour consulter et rechercher les dossiers judiciaires de l'utilisateur connect\xE9. Utilise `list_dossiers` pour lister, `search_dossiers` pour rechercher, et `get_dossier` pour obtenir le d\xE9tail complet.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_dossiers_default, search_dossiers_default, get_dossier_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
